// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/proto/foodsvc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoodService_GetMenuItemSummary_FullMethodName     = "/foodsvc.FoodService/GetMenuItemSummary"
	FoodService_BulkUpdateAvailability_FullMethodName = "/foodsvc.FoodService/BulkUpdateAvailability"
	FoodService_CreateOrder_FullMethodName            = "/foodsvc.FoodService/CreateOrder"
	FoodService_GetPendingOrderSummary_FullMethodName = "/foodsvc.FoodService/GetPendingOrderSummary"
)

// FoodServiceClient is the client API for FoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoodServiceClient interface {
	// returns a combined product summary (product + inventory + price + supplier)
	GetMenuItemSummary(ctx context.Context, in *GetMenuItemRequest, opts ...grpc.CallOption) (*MenuItemSummary, error)
	// bulk update availability for menu items, returns operations summary
	BulkUpdateAvailability(ctx context.Context, in *BulkUpdateRequest, opts ...grpc.CallOption) (*BulkUpdateResponse, error)
	// create an order
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	// get aggregated pending orders per restaurant
	GetPendingOrderSummary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PendingOrderSummary, error)
}

type foodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodServiceClient(cc grpc.ClientConnInterface) FoodServiceClient {
	return &foodServiceClient{cc}
}

func (c *foodServiceClient) GetMenuItemSummary(ctx context.Context, in *GetMenuItemRequest, opts ...grpc.CallOption) (*MenuItemSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuItemSummary)
	err := c.cc.Invoke(ctx, FoodService_GetMenuItemSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) BulkUpdateAvailability(ctx context.Context, in *BulkUpdateRequest, opts ...grpc.CallOption) (*BulkUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkUpdateResponse)
	err := c.cc.Invoke(ctx, FoodService_BulkUpdateAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, FoodService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) GetPendingOrderSummary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PendingOrderSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingOrderSummary)
	err := c.cc.Invoke(ctx, FoodService_GetPendingOrderSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodServiceServer is the server API for FoodService service.
// All implementations must embed UnimplementedFoodServiceServer
// for forward compatibility.
type FoodServiceServer interface {
	// returns a combined product summary (product + inventory + price + supplier)
	GetMenuItemSummary(context.Context, *GetMenuItemRequest) (*MenuItemSummary, error)
	// bulk update availability for menu items, returns operations summary
	BulkUpdateAvailability(context.Context, *BulkUpdateRequest) (*BulkUpdateResponse, error)
	// create an order
	CreateOrder(context.Context, *CreateOrderRequest) (*OrderResponse, error)
	// get aggregated pending orders per restaurant
	GetPendingOrderSummary(context.Context, *emptypb.Empty) (*PendingOrderSummary, error)
	mustEmbedUnimplementedFoodServiceServer()
}

// UnimplementedFoodServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoodServiceServer struct{}

func (UnimplementedFoodServiceServer) GetMenuItemSummary(context.Context, *GetMenuItemRequest) (*MenuItemSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenuItemSummary not implemented")
}
func (UnimplementedFoodServiceServer) BulkUpdateAvailability(context.Context, *BulkUpdateRequest) (*BulkUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkUpdateAvailability not implemented")
}
func (UnimplementedFoodServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedFoodServiceServer) GetPendingOrderSummary(context.Context, *emptypb.Empty) (*PendingOrderSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingOrderSummary not implemented")
}
func (UnimplementedFoodServiceServer) mustEmbedUnimplementedFoodServiceServer() {}
func (UnimplementedFoodServiceServer) testEmbeddedByValue()                     {}

// UnsafeFoodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodServiceServer will
// result in compilation errors.
type UnsafeFoodServiceServer interface {
	mustEmbedUnimplementedFoodServiceServer()
}

func RegisterFoodServiceServer(s grpc.ServiceRegistrar, srv FoodServiceServer) {
	// If the following call pancis, it indicates UnimplementedFoodServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoodService_ServiceDesc, srv)
}

func _FoodService_GetMenuItemSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).GetMenuItemSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_GetMenuItemSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).GetMenuItemSummary(ctx, req.(*GetMenuItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_BulkUpdateAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).BulkUpdateAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_BulkUpdateAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).BulkUpdateAvailability(ctx, req.(*BulkUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_GetPendingOrderSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).GetPendingOrderSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_GetPendingOrderSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).GetPendingOrderSummary(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FoodService_ServiceDesc is the grpc.ServiceDesc for FoodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foodsvc.FoodService",
	HandlerType: (*FoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenuItemSummary",
			Handler:    _FoodService_GetMenuItemSummary_Handler,
		},
		{
			MethodName: "BulkUpdateAvailability",
			Handler:    _FoodService_BulkUpdateAvailability_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _FoodService_CreateOrder_Handler,
		},
		{
			MethodName: "GetPendingOrderSummary",
			Handler:    _FoodService_GetPendingOrderSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/foodsvc.proto",
}
