// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/foodsvc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemId    int64                  `protobuf:"varint,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemRequest) Reset() {
	*x = GetMenuItemRequest{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemRequest) ProtoMessage() {}

func (x *GetMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuItemRequest) GetMenuItemId() int64 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

type MenuItemSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Restaurant     string                 `protobuf:"bytes,3,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	Availability   string                 `protobuf:"bytes,4,opt,name=availability,proto3" json:"availability,omitempty"`
	Price          string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	SupplierStatus string                 `protobuf:"bytes,6,opt,name=supplier_status,json=supplierStatus,proto3" json:"supplier_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MenuItemSummary) Reset() {
	*x = MenuItemSummary{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemSummary) ProtoMessage() {}

func (x *MenuItemSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemSummary.ProtoReflect.Descriptor instead.
func (*MenuItemSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItemSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItemSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItemSummary) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *MenuItemSummary) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

func (x *MenuItemSummary) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *MenuItemSummary) GetSupplierStatus() string {
	if x != nil {
		return x.SupplierStatus
	}
	return ""
}

type BulkUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemIds   []int64                `protobuf:"varint,1,rep,packed,name=menu_item_ids,json=menuItemIds,proto3" json:"menu_item_ids,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Concurrency   int32                  `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"` // worker pool size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateRequest) Reset() {
	*x = BulkUpdateRequest{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateRequest) ProtoMessage() {}

func (x *BulkUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateRequest.ProtoReflect.Descriptor instead.
func (*BulkUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{2}
}

func (x *BulkUpdateRequest) GetMenuItemIds() []int64 {
	if x != nil {
		return x.MenuItemIds
	}
	return nil
}

func (x *BulkUpdateRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *BulkUpdateRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type BulkUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       int32                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateResponse) Reset() {
	*x = BulkUpdateResponse{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateResponse) ProtoMessage() {}

func (x *BulkUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateResponse.ProtoReflect.Descriptor instead.
func (*BulkUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{3}
}

func (x *BulkUpdateResponse) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BulkUpdateResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemId    int64                  `protobuf:"varint,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetMenuItemId() int64 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

func (x *CreateOrderRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{5}
}

func (x *OrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PendingRestaurant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	RestaurantName string                 `protobuf:"bytes,2,opt,name=restaurant_name,json=restaurantName,proto3" json:"restaurant_name,omitempty"`
	PendingCount   int32                  `protobuf:"varint,3,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PendingRestaurant) Reset() {
	*x = PendingRestaurant{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRestaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRestaurant) ProtoMessage() {}

func (x *PendingRestaurant) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRestaurant.ProtoReflect.Descriptor instead.
func (*PendingRestaurant) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{6}
}

func (x *PendingRestaurant) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *PendingRestaurant) GetRestaurantName() string {
	if x != nil {
		return x.RestaurantName
	}
	return ""
}

func (x *PendingRestaurant) GetPendingCount() int32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

type PendingOrderSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PendingRestaurant   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingOrderSummary) Reset() {
	*x = PendingOrderSummary{}
	mi := &file_api_proto_foodsvc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingOrderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingOrderSummary) ProtoMessage() {}

func (x *PendingOrderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_foodsvc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingOrderSummary.ProtoReflect.Descriptor instead.
func (*PendingOrderSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_foodsvc_proto_rawDescGZIP(), []int{7}
}

func (x *PendingOrderSummary) GetItems() []*PendingRestaurant {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_foodsvc_proto protoreflect.FileDescriptor

const file_api_proto_foodsvc_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/foodsvc.proto\x12\afoodsvc\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\x12GetMenuItemRequest\x12 \n" +
	"\fmenu_item_id\x18\x01 \x01(\x03R\n" +
	"menuItemId\"\xb8\x01\n" +
	"\x0fMenuItemSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"restaurant\x18\x03 \x01(\tR\n" +
	"restaurant\x12\"\n" +
	"\favailability\x18\x04 \x01(\tR\favailability\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12'\n" +
	"\x0fsupplier_status\x18\x06 \x01(\tR\x0esupplierStatus\"w\n" +
	"\x11BulkUpdateRequest\x12\"\n" +
	"\rmenu_item_ids\x18\x01 \x03(\x03R\vmenuItemIds\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12 \n" +
	"\vconcurrency\x18\x03 \x01(\x05R\vconcurrency\"F\n" +
	"\x12BulkUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\"[\n" +
	"\x12CreateOrderRequest\x12 \n" +
	"\fmenu_item_id\x18\x01 \x01(\x03R\n" +
	"menuItemId\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\"B\n" +
	"\rOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x86\x01\n" +
	"\x11PendingRestaurant\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\x12'\n" +
	"\x0frestaurant_name\x18\x02 \x01(\tR\x0erestaurantName\x12#\n" +
	"\rpending_count\x18\x03 \x01(\x05R\fpendingCount\"G\n" +
	"\x13PendingOrderSummary\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.foodsvc.PendingRestaurantR\x05items2\xc9\x02\n" +
	"\vFoodService\x12M\n" +
	"\x12GetMenuItemSummary\x12\x1b.foodsvc.GetMenuItemRequest\x1a\x18.foodsvc.MenuItemSummary\"\x00\x12S\n" +
	"\x16BulkUpdateAvailability\x12\x1a.foodsvc.BulkUpdateRequest\x1a\x1b.foodsvc.BulkUpdateResponse\"\x00\x12D\n" +
	"\vCreateOrder\x12\x1b.foodsvc.CreateOrderRequest\x1a\x16.foodsvc.OrderResponse\"\x00\x12P\n" +
	"\x16GetPendingOrderSummary\x12\x16.google.protobuf.Empty\x1a\x1c.foodsvc.PendingOrderSummary\"\x00B\x11Z\x0fapi/proto;protob\x06proto3"

var (
	file_api_proto_foodsvc_proto_rawDescOnce sync.Once
	file_api_proto_foodsvc_proto_rawDescData []byte
)

func file_api_proto_foodsvc_proto_rawDescGZIP() []byte {
	file_api_proto_foodsvc_proto_rawDescOnce.Do(func() {
		file_api_proto_foodsvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_foodsvc_proto_rawDesc), len(file_api_proto_foodsvc_proto_rawDesc)))
	})
	return file_api_proto_foodsvc_proto_rawDescData
}

var file_api_proto_foodsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_foodsvc_proto_goTypes = []any{
	(*GetMenuItemRequest)(nil),  // 0: foodsvc.GetMenuItemRequest
	(*MenuItemSummary)(nil),     // 1: foodsvc.MenuItemSummary
	(*BulkUpdateRequest)(nil),   // 2: foodsvc.BulkUpdateRequest
	(*BulkUpdateResponse)(nil),  // 3: foodsvc.BulkUpdateResponse
	(*CreateOrderRequest)(nil),  // 4: foodsvc.CreateOrderRequest
	(*OrderResponse)(nil),       // 5: foodsvc.OrderResponse
	(*PendingRestaurant)(nil),   // 6: foodsvc.PendingRestaurant
	(*PendingOrderSummary)(nil), // 7: foodsvc.PendingOrderSummary
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_api_proto_foodsvc_proto_depIdxs = []int32{
	6, // 0: foodsvc.PendingOrderSummary.items:type_name -> foodsvc.PendingRestaurant
	0, // 1: foodsvc.FoodService.GetMenuItemSummary:input_type -> foodsvc.GetMenuItemRequest
	2, // 2: foodsvc.FoodService.BulkUpdateAvailability:input_type -> foodsvc.BulkUpdateRequest
	4, // 3: foodsvc.FoodService.CreateOrder:input_type -> foodsvc.CreateOrderRequest
	8, // 4: foodsvc.FoodService.GetPendingOrderSummary:input_type -> google.protobuf.Empty
	1, // 5: foodsvc.FoodService.GetMenuItemSummary:output_type -> foodsvc.MenuItemSummary
	3, // 6: foodsvc.FoodService.BulkUpdateAvailability:output_type -> foodsvc.BulkUpdateResponse
	5, // 7: foodsvc.FoodService.CreateOrder:output_type -> foodsvc.OrderResponse
	7, // 8: foodsvc.FoodService.GetPendingOrderSummary:output_type -> foodsvc.PendingOrderSummary
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_foodsvc_proto_init() }
func file_api_proto_foodsvc_proto_init() {
	if File_api_proto_foodsvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_foodsvc_proto_rawDesc), len(file_api_proto_foodsvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_foodsvc_proto_goTypes,
		DependencyIndexes: file_api_proto_foodsvc_proto_depIdxs,
		MessageInfos:      file_api_proto_foodsvc_proto_msgTypes,
	}.Build()
	File_api_proto_foodsvc_proto = out.File
	file_api_proto_foodsvc_proto_goTypes = nil
	file_api_proto_foodsvc_proto_depIdxs = nil
}
